
if (NOT DEFINED AM_PLATFORM)
    message(FATAL_ERROR "AM_PLATFORM unset" )
elseif (
    NOT AM_PLATFORM STREQUAL X86_LINUX
    AND NOT AM_PLATFORM STREQUAL EMBEDDED_LINUX
    AND NOT AM_PLATFORM STREQUAL EMBEDDED_LINUX_CC
)
    message(FATAL_ERROR "Unhandled AM_PLATFORM: ${AM_PLATFORM}" )
else()
    if (
        AM_PLATFORM STREQUAL EMBEDDED_LINUX
        OR AM_PLATFORM STREQUAL EMBEDDED_LINUX_CC
    )
        set(AM_PLATFORM_NUM 20)
        set(AM_PLATFORM_TYPE EMBEDDED_LINUX)
    else()
        set(AM_PLATFORM_NUM 10)
        set(AM_PLATFORM_TYPE LINUX)
    endif()

    message("Using host: ${AM_PLATFORM}")
    message("Using platform: ${AM_PLATFORM_TYPE}")
    message("Using platform number: ${AM_PLATFORM_NUM}")

    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DPLATFORM_LINUX=10")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DPLATFORM_EMBEDDED_LINUX=20")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_AM_PLATFORM_=${AN_PLATFORM_NUM}")
endif()
